load("../data/ABIDE_fALFF_2.RData")
write.table(fALFF, file = "../data/fALFF.csv",row.names=FALSE, na="",col.names=FALSE, sep=",")
write.table(phenotype_data, file = "../data/phenotype_data.csv",row.names=FALSE, na="",col.names=FALSE, sep=",")
write.table(coord, file = "../data/coord.csv",row.names=FALSE, na="",col.names=FALSE, sep=",")
write.table(region_code, file = "../data/region_code.csv",row.names=FALSE, na="",col.names=FALSE, sep=",")
write.table(region_name, file = "../data/region_name.csv",row.names=FALSE, na="",col.names=FALSE, sep=",")
